= 画像可逆圧縮手法 FLIF についてのメモ

https://flif.info/[FLIF (Free Lossless Image Format)] は、実用されている可逆圧縮形式としておそらく最強の圧縮手法です。実際、画像圧縮手法に関する最近の研究では、 FLIF が比較対象となることが多いように思われます。このブログ記事では、 FLIF がどのように圧縮を行っているのか、理解できた範囲で記録していきます。

ファイル形式としての特徴は、アルファチャンネル対応やアニメーション対応など、現代的な画像形式として一般的な構成となっています。

圧縮手法としての特徴は、次の2点が挙げられます。

. 色空間 (YCoCg) や画素値の範囲を変換することで、画素間の相関が大きくなり、効率よく符号化できるようにします。
. エントロピー符号化に使用する確率分布の使い分け（コンテキスト）を入力画像から決定木の形式で学習します。

FLIF は、すでに ImageMagick で実装されており、すぐに試すことができます。また、コーデックのリファレンス実装は GitHub にあります (https://github.com/FLIF-hub/FLIF:[FLIF-hub/FLIF])。

なお、現在 FLIF の開発はストップしており、 FLIF の成果は JPEG XL に取り込まれるようです。ただ https://gitlab.com/wg1/jpeg-xl/-/blob/bf10dc87f9b91cf2eb536b36362987a992b3c25f/doc/xl_overview.md#lossless:[JPEG XL の説明]を読む限り、以上に挙げた特徴とは違っているので、手法としては別物になるのではないかと思っています。

== 他の可逆圧縮手法との比較

（あんまり詳しくないので、ツッコミよろ）

現在 web でシェアを取っている PNG と WebP は、 Deflate のような辞書型圧縮が使用されています。 PNG は入力画像の画素値、または入力画像に何らかのフィルタをかけた画像の画素値を Deflate で圧縮します。 WebP の可逆圧縮モードでは隣接画素を使った画素値の予測をし、予測値の誤差（残差）を記録します。

FLIF は、隣接画素からの予測誤差を使用する点で WebP に近いですが、 WebP のような辞書型圧縮 + ハフマン符号の構成ではなく、算術符号で符号化を行います。算術符号については後で説明します。

算術符号を使用する手法としては、 JPEG 2000 や H.264 があります。これらの手法では、2値に対する算術符号が使用されています。 FLIF もこれらの手法を参考にし、ギリギリ特許と被らない手法（FFV1 で導入）を使用しています。

== FLIF ファイルの構成

FLIF ファイルは、大きく次のように構成されます。区切り方は https://flif.info/spec.html:[FLIF16 Specification] に従っています。

Main Header:: 画像の大きさやチャンネル数が記述されます。
Metadata:: 任意のデータを書き込めます。ここに Exif とかを入れます。
Second Header:: 圧縮に使用するパラメータが記述されます。ここで色空間やその他の変換をするのか、するならば変換に使用するパラメータを記述します。
Pixel Data:: Second Header で指定した変換がなされた画像のデータです。後で詳しく説明します。

== インターレースエンコーディング

== 符号化

=== 算術符号

=== 適応的算術符号

=== MANIAC
