name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: yarn install
        run: yarn install --pure-lockfile

      - name: yarn build
        run: yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: blog.azyobuzi.net
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
