name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - run: npm ci --production=false
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: blog.azyobuzi.net
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
