name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install --production=false
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: blog.azyobuzi.net
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: npm install
        run: npm install --production=false
      - name: tsc
        run: npm run -w generator check
      - name: jest
        run: npm test -w generator
