name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: apt-get install
        run: sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - run: npm ci --production=false
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: blog.azyobuzi.net
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
