name: gh-pages diff

on:
  pull_request:
    branches: [master]

jobs:
  diff:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/package-lock.json
      - name: apt-get install
        run: sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - run: npm ci --production=false
        working-directory: src
      - run: npm run build
        working-directory: src
      - name: Diff
        id: diff
        run: |
          rm -rf gh-pages/.git gh-pages/.nojekyll gh-pages/CNAME
          echo '### gh-pages diff' >> $GITHUB_STEP_SUMMARY
          echo '```patch' >> $GITHUB_STEP_SUMMARY
          diff -ru gh-pages src/public | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
